name: Verify Changes
on:
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master

jobs:
  install:
    name: Install on Ubuntu
    runs-on: [ubuntu-latest]

    steps:
      - name: Pre-Install zsh on Ubuntu
        run: sudo apt-get update; sudo apt-get install zsh; sudo chsh -s zsh
      - name: Install ohmyzsh on ubuntu
        run: sh -c ./install.sh --unattended && exit 0
